### ISSUE TITLE
NumberFormatException: Invalid int: "9497000000"

### ISSUE THREAD

**Issue by eileenfan** [demantz/RFAnalyzer#58]
//package name: com.mantz_it.rfanalyzer
//version: 1.11
//target sdk version: android-18
 java.lang.RuntimeException: Unable to resume activity {com.mantz_it.rfanalyzer/com.mantz_it.rfanalyzer.MainActivity}: java.lang.NumberFormatException: Invalid int: "9497000000"
 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2790)
 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2819)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1298)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.NumberFormatException: Invalid int: "9497000000"
 	at java.lang.Integer.invalidInt(Integer.java:138)
 	at java.lang.Integer.parse(Integer.java:378)
 	at java.lang.Integer.parseInt(Integer.java:366)
 	at java.lang.Integer.parseInt(Integer.java:332)
 	at java.lang.Integer.valueOf(Integer.java:490)
 	at com.mantz_it.rfanalyzer.MainActivity.checkForChangedPreferences(MainActivity.java:490)
 	at com.mantz_it.rfanalyzer.MainActivity.onStart(MainActivity.java:371)
 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
 	at android.app.Activity.performStart(Activity.java:5143)
 	at android.app.Activity.performRestart(Activity.java:5198)
 	at android.app.Activity.performResume(Activity.java:5203)
 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2780)

**Comment by wissanu020430** [comment]
https://github.com/demantz/RFAnalyzer/issues/69#issuecomment-499084698

**Comment by wissanu020430** [comment]
https://github.com/demantz/RFAnalyzer/issues/69#issuecomment-499084698
